FROM python:3.8

WORKDIR /app

ARG ALPHADEFI_MONGO
ARG ALPHADEFI_WALLET
ARG CMC_API
ARG EOD_API

ENV ALPHADEFI_MONGO=$ALPHADEFI_MONGO
ENV ALPHADEFI_WALLET=$ALPHADEFI_WALLET
ENV CMC_API=$CMC_API
ENV EOD_API=$EOD_API

COPY Scripts/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .

CMD ["python", "Scripts/collectData.py"]